# Generated by Django 5.2.5 on 2025-09-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterModelTable(
            name='event',
            table='event',
        ),
    ]
