# Generated by Django 5.2.5 on 2025-09-02 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_studentprofile_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('interaction_type', models.CharField(choices=[('CALL', 'Call'), ('INTERVIEW', 'Interview'), ('CV_UPDATE', 'CV Update'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('ANSWERED', 'Answered'), ('MISSED', 'Missed'), ('COMPLETED', 'Completed'), ('PENDING', 'Pending')], max_length=20)),
                ('instructor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.studentprofile')),
            ],
            options={
                'db_table': 'progress_log',
            },
        ),
    ]
