# Generated by Django 5.2.5 on 2025-09-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_progresslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresslog',
            name='status',
            field=models.CharField(choices=[('ANSWERED', 'Answered'), ('MISSED', 'Missed'), ('COMPLETED', 'Completed'), ('PENDING', 'Pending')], default='PENDING', max_length=20),
        ),
    ]
